### ISSUE TITLE
Unzipping doesn

### ISSUE THREAD

**Issue by parkerha** [Markxxx7/Sentence-Factory#1]
Oops accidentally pressed enter and didn't finish the title. But anyway, when I try unzipping the program it doesn't bring Sentence Factory.exe with it. It unzips everything else. I think my computer thinks it is a virus because I've tried removing the .exe and putting it directly into the unzipped folder with everything else, but it won't let me open it, saying that it is a virus. Any ideas of what to do? I've tried running as administrator, pressing the "run anyway" button, etc.

**Comment by Markxxx7** [comment]
Did you download the zip from mega? Was the sentence factory.exe there in the folder but you couldn’t run it or was it not there at all? Could you send an image of the full error? I’ll try to figure out what went wrong. Did you watch the YouTube video? Thanks for sharing.

**Comment by parkerha** [comment]
Yes I downloaded the zip from mega and sentence factory.exe was in the zipped folder, but when I extracted it, it was not in the unzipped folder. I watched the YouTube video and followed the steps directly. First screenshot is after extracting zip, second is copying and pasting .exe into extracted folder and trying to run it. Also, my computer is in Spanish for immersion, sorry if you can't understand what it's saying, but the error basically says there's a virus or potentially undesired software so it can't complete the operation. 
![Screenshot_2](https://user-images.githubusercontent.com/57109711/67705245-ab830300-f984-11e9-82e4-1b168cbde4cf.png)
![Screenshot_3](https://user-images.githubusercontent.com/57109711/67705396-ebe28100-f984-11e9-92d4-2dd24c1006e2.png)

**Comment by Markxxx7** [comment]
Oh I'm completely stumped. Is there any way you can allow it to run? Do you have an anti-virus installed? Also the exe is basically just running main.py so if it doesn't bother you too much, could you run main.py with your python interpreter, cause it looks like you have python installed, until I find a fix. The exe is basically just a .bat file running the main.py so for some reason its showing up as a virus. I'll look into the exe thing because it works on my machine without the virus thing showing up. So I'll update the mega link with an updated .exe file. Sorry about that, python is pretty annoying when trying to make it into an exe.

**Comment by parkerha** [comment]
Lol okay, had to work on college stuff today but now I am back trying to figure this out. My new error is this: 
![Screenshot_4](https://user-images.githubusercontent.com/57109711/67741611-ba4ed180-f9e7-11e9-8683-ee7bbd5d6905.png)
I have windows antivirus off. Everything is now extracting correctly but I don't know what's going wrong otherwise. Thanks for all your help by the way. And yes I took a class in python for my degree (physics) but I'm terrible at it so I'm unable to open the code and understand what is wrong.

**Comment by Markxxx7** [comment]
Nothing is wrong with the code, its just your windows version. But its still fixable as a I found a fix. Go to my pinned comment in that youtube video, and follow the last step. Lol I'm so glad I found a fix because for some reason it doesn't run on anything other than the latest version

**Comment by Markxxx7** [comment]
Yup all ready to go! I updated all the links and this time it has to work for sure. Thanks for the patience.

**Comment by parkerha** [comment]
Now it's looking for the python in your computer's route? I think that's what this means at least. I'm so confused lol 

![Screenshot_5](https://user-images.githubusercontent.com/57109711/67815303-97b6ca00-fa74-11e9-876c-be1952e93269.png)

**Comment by Markxxx7** [comment]
Oh okay I think I get it. Looks like you cannot run this python program without having python installed at all, lol i thought it was possible to make an exe but nope. Looks like most people aren't going to have python installed so I don't think this is going to work. So sorry about that,
